name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - run: rustup component add clippy rustfmt llvm-tools
      - run: cargo install grcov cargo-mutants just
      - uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
      - run: cargo fmt --check
      - run: just clippy coverage
      - run: just mutants
